import {
  PatientProfile,
  MedicalRecord,
  AccessGrant,
  AuditLogEntry,
  LoginHistoryEntry,
  GranularPermissions,
} from '../types/medical';

export const INITIAL_PATIENT: PatientProfile = {
  id: 'PAT-948201',
  fullName: 'Priya Sharma',
  age: 32,
  dob: '1994-04-18',
  gender: 'Female',
  bloodType: 'O+ (O-Positive)',
  email: 'priya.sharma@medivault.io',
  phone: '+91 98765 43210',
  address: '42 Lotus Gardens, Indiranagar, Bengaluru, KA 560038',
  emergencyContact: {
    id: 'cnt-1',
    name: 'Rajesh Sharma',
    relationship: 'Brother / Designated Proxy',
    phone: '+91 98123 45678',
    email: 'rajesh.sharma@gmail.com',
    isTrustedProxy: true,
  },
  trustedContacts: [
    {
      id: 'cnt-1',
      name: 'Rajesh Sharma',
      relationship: 'Brother',
      phone: '+91 98123 45678',
      email: 'rajesh.sharma@gmail.com',
      isTrustedProxy: true,
    },
    {
      id: 'cnt-2',
      name: 'Ananya Sharma',
      relationship: 'Sister',
      phone: '+91 98987 65432',
      email: 'ananya.s@gmail.com',
      isTrustedProxy: true,
    },
  ],
  allergies: [
    {
      id: 'alg-1',
      allergen: 'Penicillin',
      severity: 'Life-Threatening',
      reaction: 'Anaphylaxis, Severe Hives, Airway Swelling',
    },
    {
      id: 'alg-2',
      allergen: 'Peanuts',
      severity: 'Moderate',
      reaction: 'Local Urticaria, Facial Flushing, GI Distress',
    },
  ],
  chronicConditions: [
    {
      id: 'cnd-1',
      name: 'Type 2 Diabetes Mellitus',
      diagnosedYear: '2022',
      status: 'Managed',
    },
    {
      id: 'cnd-2',
      name: 'Mild Vitamin D Deficiency',
      diagnosedYear: '2023',
      status: 'Active',
    },
  ],
  joinedDate: '2023-01-15',
};

export const INITIAL_GRANULAR_PERMISSIONS: GranularPermissions = {
  bloodGroup: true,
  allergies: true,
  currentMedicines: true,
  chronicDiseases: true,
  labReports: true,
  prescriptions: true,
  imagingReports: true,
  vaccinationHistory: true,
  surgeryHistory: true,
  mentalHealthRecords: false, // Private by default
};

export const INITIAL_RECORDS: MedicalRecord[] = [
  {
    id: 'REC-2026-101',
    title: 'Type 2 Diabetes Quarterly Evaluation & Insulin Titration',
    category: 'Prescription',
    date: '2026-06-15',
    diagnosingDoctor: 'Dr. Amit Roy',
    doctorSpecialty: 'Endocrinology',
    hospitalClinic: 'Apollo Hospital',
    diagnosisDetails: 'Glycemic levels stable on combination therapy. HbA1c improved to 6.8%. Fasting glucose 118 mg/dL.',
    medicines: [
      {
        id: 'med-1',
        name: 'Metformin',
        dosage: '500mg',
        frequency: 'Twice Daily (Post-Meals)',
        duration: '90 Days',
        instructions: 'Take after breakfast and dinner with plenty of water.',
        doctor: 'Dr. Amit Roy',
        hospital: 'Apollo Hospital',
        startDate: '2026-06-15',
        status: 'Active',
      },
      {
        id: 'med-2',
        name: 'Insulin Glargine (Lantus)',
        dosage: '12 Units',
        frequency: 'Once Daily at Bedtime',
        duration: 'Ongoing',
        instructions: 'Subcutaneous injection into abdomen rotation sites.',
        doctor: 'Dr. Amit Roy',
        hospital: 'Apollo Hospital',
        startDate: '2026-06-15',
        status: 'Active',
      },
    ],
    notes: 'Patient advised to log daily fasting blood sugar readings in app.',
    tags: ['Diabetes', 'Endocrinology', 'Prescription'],
    isPrivateFromEmergency: false,
    fileUrl: 'prescription_metformin_insulin.pdf',
    fileSize: '1.2 MB',
  },
  {
    id: 'REC-2026-088',
    title: 'Acute Fever & Viral Upper Respiratory Consult',
    category: 'Prescription',
    date: '2026-04-10',
    diagnosingDoctor: 'Dr. Sneha Das',
    doctorSpecialty: 'Internal Medicine',
    hospitalClinic: 'City Care Hospital',
    diagnosisDetails: 'Mild viral pyrexia with throat irritation. Chest clear on auscultation.',
    medicines: [
      {
        id: 'med-3',
        name: 'Crocin (Paracetamol)',
        dosage: '650mg',
        frequency: 'Every 6 Hours as needed',
        duration: '5 Days',
        instructions: 'Do not exceed 4 tablets in 24 hours.',
        doctor: 'Dr. Sneha Das',
        hospital: 'City Care Hospital',
        startDate: '2026-04-10',
        status: 'Completed',
      },
      {
        id: 'med-4',
        name: 'Vitamin D3 (Cholecalciferol)',
        dosage: '60,000 IU',
        frequency: 'Once Weekly',
        duration: '8 Weeks',
        instructions: 'Take with milk or fatty meal for optimal absorption.',
        doctor: 'Dr. Sneha Das',
        hospital: 'City Care Hospital',
        startDate: '2026-04-10',
        status: 'Active',
      },
    ],
    notes: 'Fever subsided after 48 hours. Continue Vitamin D supplementation.',
    tags: ['Fever', 'Internal Medicine', 'General'],
    isPrivateFromEmergency: false,
    fileUrl: 'city_care_fever_consult.pdf',
    fileSize: '840 KB',
  },
  {
    id: 'REC-2026-045',
    title: 'Comprehensive Metabolic Panel & Lipid Blood Report',
    category: 'Blood Report',
    date: '2026-03-02',
    diagnosingDoctor: 'Dr. Sneha Das',
    doctorSpecialty: 'Pathology & Diagnostics',
    hospitalClinic: 'City Care Hospital',
    diagnosisDetails: 'Fasting Plasma Glucose: 115 mg/dL, HbA1c: 6.9%, Total Cholesterol: 178 mg/dL, HDL: 52 mg/dL, LDL: 98 mg/dL, Triglycerides: 140 mg/dL.',
    medicines: [],
    notes: 'Kidney and Liver Function Tests within normal limits.',
    tags: ['Blood Report', 'Lab Result', 'Diagnostics'],
    isPrivateFromEmergency: false,
    fileUrl: 'blood_report_march_2026.pdf',
    fileSize: '2.4 MB',
  },
  {
    id: 'REC-2025-132',
    title: 'Lumbar Spine X-Ray Imaging Report',
    category: 'X-ray',
    date: '2025-11-20',
    diagnosingDoctor: 'Dr. Rajesh Nair',
    doctorSpecialty: 'Radiology',
    hospitalClinic: 'Apollo Hospital',
    diagnosisDetails: 'Normal vertebral body alignment. No acute fracture or disc space narrowing noted. Mild muscle strain.',
    medicines: [],
    notes: 'Recommended core strengthening exercise routine.',
    tags: ['X-Ray', 'Radiology', 'Spine'],
    isPrivateFromEmergency: false,
    fileUrl: 'xray_lumbar_spine.png',
    fileSize: '4.8 MB',
  },
  {
    id: 'REC-2025-090',
    title: 'Annual Influenza & COVID-19 Booster Vaccination',
    category: 'Vaccination Record',
    date: '2025-09-14',
    diagnosingDoctor: 'Dr. Sneha Das',
    doctorSpecialty: 'Preventive Care',
    hospitalClinic: 'City Care Hospital',
    diagnosisDetails: 'Administered Quadrivalent Flu Vaccine (0.5ml IM) and mRNA COVID Booster.',
    medicines: [],
    notes: 'No adverse reaction during 15-minute observation period.',
    tags: ['Vaccination', 'Immunization', 'Preventive'],
    isPrivateFromEmergency: false,
    fileUrl: 'vaccination_certificate.pdf',
    fileSize: '620 KB',
  },
  {
    id: 'REC-2025-030',
    title: 'Private Mental Wellness & Work Stress Evaluation',
    category: 'Mental Health',
    date: '2025-03-12',
    diagnosingDoctor: 'Dr. Meera Menon',
    doctorSpecialty: 'Psychiatry & Behavioral Health',
    hospitalClinic: 'MindCare Clinic',
    diagnosisDetails: 'Mild situational anxiety associated with work pressure. Sleep hygiene counseling provided.',
    medicines: [],
    notes: 'Marked strictly PRIVATE by Priya Sharma. Excluded from general emergency exports.',
    tags: ['Mental Health', 'Private', 'Psychiatry'],
    isPrivateFromEmergency: true, // Marked private by patient
    fileUrl: 'wellness_consult_confidential.pdf',
    fileSize: '1.1 MB',
  },
];

export const INITIAL_GRANTS: AccessGrant[] = [
  {
    id: 'GRT-8821',
    doctorName: 'Dr. Amit Roy',
    specialty: 'Endocrinology',
    hospital: 'Apollo Hospital',
    grantedAt: '2026-07-24 14:00',
    expiresAt: '2026-07-24 16:00 (Expires in 2 hours)',
    status: 'active',
    accessType: 'Direct Doctor Access',
  },
  {
    id: 'GRT-4912',
    doctorName: 'Dr. Sneha Das',
    specialty: 'Internal Medicine',
    hospital: 'City Care Hospital',
    grantedAt: '2026-07-24 09:00',
    expiresAt: '2026-07-25 09:00 (Expires tomorrow)',
    status: 'active',
    accessType: 'Hospital Portal',
  },
  {
    id: 'GRT-1029',
    doctorName: 'Dr. Rajesh Nair',
    specialty: 'Radiology',
    hospital: 'Apollo Hospital',
    grantedAt: '2025-11-20 10:00',
    expiresAt: '2025-12-20 10:00',
    status: 'expired',
    accessType: 'Hospital Portal',
  },
];

export const INITIAL_LOGIN_HISTORY: LoginHistoryEntry[] = [
  {
    id: 'SES-901',
    timestamp: '2026-07-24 21:10:00',
    device: 'Apple MacBook Pro M3 (macOS)',
    browser: 'Chrome 126.0',
    location: 'Bengaluru, India (103.14.24.89)',
    ipAddress: '103.14.24.89',
    status: 'Success',
    isCurrentSession: true,
  },
  {
    id: 'SES-890',
    timestamp: '2026-07-24 10:15:22',
    device: 'iPhone 15 Pro (iOS 17.5)',
    browser: 'MediVault Mobile App v1.4',
    location: 'Bengaluru, India (103.14.24.89)',
    ipAddress: '103.14.24.89',
    status: 'Success',
    isCurrentSession: false,
  },
  {
    id: 'SES-872',
    timestamp: '2026-07-22 18:44:10',
    device: 'Windows Workstation (Win 11)',
    browser: 'Firefox 125.0',
    location: 'Mumbai, India (49.36.12.44)',
    ipAddress: '49.36.12.44',
    status: 'Success',
    isCurrentSession: false,
  },
  {
    id: 'SES-850',
    timestamp: '2026-07-20 03:12:09',
    device: 'Unknown Device (Linux)',
    browser: 'Automated Script Bot',
    location: 'Frankfurt, Germany (185.220.101.4)',
    ipAddress: '185.220.101.4',
    status: 'Failed Warning',
    isCurrentSession: false,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'LOG-991',
    timestamp: '2026-07-24 14:05:30',
    actorName: 'Dr. Amit Roy',
    actorRole: 'Cardiologist',
    action: 'Viewed Records',
    details: 'Accessed Type 2 Diabetes treatment records and recent metabolic panel at Apollo Hospital.',
    ipAddress: '103.14.24.89 (Apollo Hospital Terminal)',
  },
  {
    id: 'LOG-990',
    timestamp: '2026-07-24 09:00:00',
    actorName: 'Priya Sharma',
    actorRole: 'Patient',
    action: 'Created Emergency Token',
    details: 'Generated 1-Hour self-destructing access token (MV-PRIYA-982) for City Care ER staff.',
    ipAddress: '103.14.24.89 (Patient Client)',
  },
  {
    id: 'LOG-989',
    timestamp: '2026-07-23 16:30:12',
    actorName: 'Priya Sharma',
    actorRole: 'Patient',
    action: 'Updated Privacy Toggles',
    details: 'Marked "Private Mental Wellness Consult" to PRIVATE. Excluded from general emergency payload.',
    ipAddress: '103.14.24.89 (Patient Client)',
  },
  {
    id: 'LOG-988',
    timestamp: '2026-07-22 11:20:00',
    actorName: 'Rajesh Sharma',
    actorRole: 'Trusted Contact Proxy',
    action: 'Trusted Proxy Approved Access',
    details: 'Rajesh Sharma verified 2FA OTP and granted 1-hour emergency access to Dr. Sneha Das.',
    ipAddress: '103.14.24.89 (Trusted Contact Proxy App)',
  },
];
